apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- monitoring-alert.yaml
- monitoring-helmrelease.yaml
- monitoring-gitrepository.yaml
- grafana-datasource-jaeger.yaml
- slack-provider.yaml
- slack-notif-alert.yaml
- grafana-dashboard-networkpolicies.yaml


