apiVersion: v1
data:
  credentials.json: eyJBY2NvdW50VGFnIjoiN2I4MWNhM2JiM2NlZjY2YjUyNzk0OTg2NWFlN2UxMjgiLCJUdW5uZWxTZWNyZXQiOiJwbE1INFc0MVg0dkI4SWpjOHNXRXczeXdxSVhydmZLNHBTTi9tSEFoQytVPSIsIlR1bm5lbElEIjoiYzI0ZTUyNDEtYmVjZi00ZTJiLWFlM2ItN2NmNDdhNGY1ZDBlIiwiRW5kcG9pbnQiOiIifQ==
kind: Secret
metadata:
  creationTimestamp: "2025-12-09T01:09:34Z"
  name: cloudflare-tunnel-credentials-grafana
  namespace: monitoring
  resourceVersion: "103123"
  uid: 41739f80-9833-4228-a191-bd22900915ec
type: Opaque
